spring:
  application:
    name: book-service

server:
  port:
    0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

evaluations.service.id: book-evaluation